### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by pkshultz**
Correct spelling: "controlled", not "controled"

### CODE REVIEW

**Comment by mathisonian** [comment]
could you target the `src` branch with this fix? Relevant section is here: https://github.com/lightning-viz/lightning-viz.github.io/blob/src/src/templates/visualizations/3d/index.jade#L57

**Comment by pkshultz** [comment]
Absolutely! My apologies on not seeing it.

**Comment by pkshultz** [comment]
[#11](https://github.com/lightning-viz/lightning-viz.github.io/pull/11)

**Comment by mathisonian** [comment]
closed by #11

**Pull request closed without merging**
