### PR TITLE
New landing page

### PR DESCRIPTION
**Pull request by freeman-lab**
Drops the old landing page for something that's more integrated with the main documentation. Required some reorganization.

screen shot 2015-08-24 at 8 21 55 pm

### CODE REVIEW

**Comment by mathisonian** [comment]
For reference:

**current landing page**
screencapture-lightning-viz-org-1440520231855

**proposed**
screencapture-localhost-8000-1440520270423

**Comment by mathisonian** [comment]
This is looking great, way more concise and +1 to integrating the styles with the rest of the docs.

A couple tweaks (that I'm happy to implement if people agree):
- Move the github button, it floating a bit now (maybe put it next to the bolt in the sidebar)
- Align the columns for the intro text and client libraries
- We have 2 different shades of purple on the page now, it would be good to just have 1

**Comment by mathisonian** [comment]
@andrewps would you be willing to give any feedback / comments on this?

**Comment by freeman-lab** [comment]
+1 to all those, some were due to my not planning for a larger screen! easy for me to fix those things (but also feel free to mess with it)

**Comment by mathisonian** [comment]
Sounds good! The last thing would be to test on mobile and do any necessary updates there :phone:

**Comment by paulathevalley** [comment]
This looks nice! +1 on the above as well. 

There are a lot of different combinations of font weights and sizes, so it’s feeling a little less cohesive as a unit. Limiting the number of combinations may bring everything together as a family—for example, maybe only the Lightning heading is bold, and everything else is regular weight. Maybe there are only three or four font sizes. 

I expected the images to link to one of the visualizations, like an Explore mode, because they look cool. I also really like the phrase "Getting Started" as it would be a clear first click for newbies, and I see the phrase often. These are my expectations that can be easily changed, though! :)

**Comment by freeman-lab** [comment]
@paulathevalley really awesome feedback, thank you! Agree with all of this. Putting together some changes now and will post a new version here.

**Comment by freeman-lab** [comment]
Several updates to address all the comments, thanks again @paulathevalley @mathisonian for the feedback!

screen shot 2015-08-27 at 5 01 52 pm

design

**Comment by mathisonian** [comment]
:100: :100: :100: this looks great! thanks @paulathevalley for the review

**Comment by freeman-lab** [comment]
Ok, fixed the hover styles, and confirmed it responds well on mobile. Merging this in, will of course need to fill-in/update all the links as we finish the rest of the doc updates.

**Comment by paulathevalley** [comment]
:star2: :star2: :star2:

**Comment by freeman-lab** [comment]
thanks @paulathevalley ! designing collaboratively in a PR is fun, should do more often =)

**Pull request merged**
